language: go

notificaitons:
  email:
    recipients: roberto.romero@safelayer.com
    on_success: always
    on_failure: always

addons:
  sonarcloud:
    organization: "robertoromeroi"
    token:
      secure: $SONAR_TOKEN

branches:
  only:
    - master
    - develop

before_script:
- go get github.com/bmizerany/assert

script:
- go test -v

script:
  - sonar-scanner
